### ISSUE TITLE
The layout of the main calendar page is confusing

### ISSUE THREAD

**Issue by jacobalexanderreed** [quizbowl/collegecalendar#1]
I think there's too much information in the main season calendar table when you first open it. If you don't know what you're looking for, it takes a long time to figure out what and where everything is, and then it takes a lot of scrolling (in two dimensions!) to get to things.

This shouldn't be too hard to fix—I think just collapsing even more information (e.g. the mirrors list) by default would do the trick. Maybe use colors to set the mirrors list off from all the other info?

Or maybe make it possible to sign up for an account and/or select your region first, so that the mirrors list only gives you relevant information?

Anyway, this is an absolutely amazing resource, and the map is the coolest fucking thing.

**Comment by hftf** [comment]
Thanks for all of these great suggestions. I've split off a few of them into separate issues, so that they can be discussed and resolved individually:

* #2 Eliminate horizontal scrolling
* #3 Customize which regions are displayed
* #4 Collapse even more rows by default

I’ll assign #3 and #4 to myself.
