### ISSUE TITLE
West Virginia

### ISSUE THREAD

**Issue by adamisch** [quizbowl/collegecalendar#7]
West Virginia is colored in, with no dots, as if there is no school in West Virginia that plays quizbowl. However, it looks like [there now is](http://hdwhite.org/qb/stats/team/west+virginia).

**Comment by hftf** [comment]
Last month, I added a dot for WVU and extended the Eastern Midwest region to include one county in West Virginia (the one containing WVU); see 646985a. I don’t know of any school in the remaining area of West Virginia that plays college quizbowl – it isn’t shaded because empirically we don’t really know where (i.e. which existing region) a college in West Virginia would typically go to play college quizbowl. (And it’s hard to make a case from 2 solo teams and a forfeit.) Feel free to change the map, though.
